"""create core tables

Revision ID: e078399f255c
Revises: 
Create Date: 2026-10-08 23:47:17.343240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e078399f255c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('app_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.Column('has_achievements', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('app_id')
    )
    op.create_table('players',
    sa.Column('steam_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('persona_name', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('profile_url', sa.String(), nullable=True),
    sa.Column('visibility', sa.SmallInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('steam_id')
    )
    op.create_table('achievements',
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('api_name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.Column('hidden', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['games.app_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('app_id', 'api_name')
    )
    op.create_table('player_games',
    sa.Column('steam_id', sa.BigInteger(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('playtime_minutes', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('recent_playtime_minutes', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_played_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['games.app_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['steam_id'], ['players.steam_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('steam_id', 'app_id')
    )
    op.create_table('player_achievements',
    sa.Column('steam_id', sa.BigInteger(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('api_name', sa.String(), nullable=False),
    sa.Column('achieved', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['app_id', 'api_name'], ['achievements.app_id', 'achievements.api_name'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['steam_id'], ['players.steam_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('steam_id', 'app_id', 'api_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_achievements')
    op.drop_table('player_games')
    op.drop_table('achievements')
    op.drop_table('players')
    op.drop_table('games')
    # ### end Alembic commands ###
